/**
 * Словарь для идентификаторов комнат.
 *
 * Идентификатор диктуют вслух, поэтому слов, различающихся одной буквой,
 * здесь нет: ошибка в одной букве делает комнату нечитаемой, а понять это
 * можно будет только по пустой истории.
 *
 * Ровно 1024 слов — степень двойки. Иначе выборка по модулю сместила бы
 * распределение, и заявленная стойкость перестала бы быть правдой.
 *
 * Сгенерирован build-wordlist.py — править руками не нужно.
 */

export const WORDS = [
  'able', 'acid', 'acorn', 'actor', 'adapt', 'admit', 'adobe', 'adult',
  'after', 'again', 'agent', 'agree', 'ahead', 'alarm', 'album', 'alert',
  'algae', 'alien', 'alike', 'alley', 'allow', 'almond', 'alone', 'alpha',
  'amber', 'amble', 'amend', 'amino', 'among', 'amuse', 'anchor', 'angel',
  'angle', 'animal', 'annual', 'answer', 'anvil', 'apart', 'apex', 'apple',
  'april', 'apron', 'aqua', 'arbor', 'arcade', 'arch', 'arctic', 'area',
  'argue', 'army', 'aroma', 'array', 'arrow', 'artist', 'ash', 'aside',
  'aspect', 'asset', 'atlas', 'atom', 'attic', 'auburn', 'audio', 'august',
  'aunt', 'auto', 'avatar', 'avenue', 'avid', 'awake', 'award', 'away',
  'axis', 'axle', 'bacon', 'badge', 'bagel', 'baker', 'balance', 'balcony',
  'balloon', 'bamboo', 'banana', 'banjo', 'banner', 'barn', 'barrel', 'basil',
  'basket', 'batch', 'baton', 'beach', 'beacon', 'beam', 'beard', 'beast',
  'beaver', 'beef', 'begin', 'behind', 'bell', 'benefit', 'berry', 'beside',
  'beta', 'beyond', 'bicycle', 'binary', 'bingo', 'birch', 'bird', 'biscuit',
  'bishop', 'bison', 'bitter', 'black', 'blade', 'blanket', 'blast', 'blaze',
  'bleach', 'blend', 'bless', 'blink', 'block', 'blood', 'blossom', 'blue',
  'blush', 'board', 'boat', 'body', 'boil', 'bond', 'bonus', 'book',
  'boost', 'border', 'born', 'borrow', 'bottle', 'bottom', 'bounce', 'bow',
  'brace', 'brain', 'branch', 'brand', 'brass', 'bread', 'breeze', 'brick',
  'bridge', 'brief', 'bright', 'bring', 'bronze', 'brook', 'brother', 'brown',
  'brush', 'bubble', 'bucket', 'budget', 'buffalo', 'build', 'bulb', 'bundle',
  'bunker', 'burden', 'burst', 'bush', 'button', 'buyer', 'buzz', 'cabin',
  'cable', 'cactus', 'cage', 'calm', 'camel', 'camera', 'camp', 'canal',
  'candle', 'candy', 'canoe', 'canvas', 'canyon', 'cape', 'captain', 'carbon',
  'cargo', 'carpet', 'carrot', 'carve', 'cash', 'castle', 'catch', 'cause',
  'cedar', 'celery', 'cement', 'census', 'center', 'century', 'ceramic', 'chain',
  'chalk', 'champion', 'chance', 'channel', 'chaos', 'chapel', 'chapter', 'charge',
  'charm', 'chase', 'cheap', 'check', 'cheese', 'chef', 'cherry', 'chess',
  'chief', 'child', 'chimney', 'chip', 'chisel', 'choice', 'choose', 'chorus',
  'chrome', 'chunk', 'cider', 'cigar', 'cinema', 'circle', 'circus', 'citizen',
  'city', 'civic', 'claim', 'clamp', 'clan', 'clash', 'clerk', 'clever',
  'cliff', 'climb', 'clinic', 'clip', 'cloak', 'clone', 'cloth', 'cloud',
  'club', 'cluster', 'clutch', 'coach', 'coal', 'coast', 'cobalt', 'cobra',
  'cocoa', 'coffee', 'coil', 'cold', 'collar', 'colony', 'color', 'column',
  'comb', 'comet', 'comfort', 'comic', 'command', 'comment', 'common', 'compact',
  'company', 'compare', 'compass', 'compete', 'concept', 'conduct', 'cone', 'confirm',
  'connect', 'consider', 'console', 'constant', 'contact', 'contain', 'content', 'control',
  'convert', 'cook', 'copper', 'coral', 'cord', 'corner', 'correct', 'cotton',
  'couch', 'council', 'count', 'couple', 'courage', 'course', 'court', 'cousin',
  'cover', 'cowboy', 'coyote', 'cozy', 'crab', 'crack', 'cradle', 'craft',
  'crane', 'crash', 'crater', 'crawl', 'crazy', 'cream', 'create', 'credit',
  'creek', 'crew', 'cricket', 'crime', 'crisp', 'critic', 'crop', 'cross',
  'crowd', 'crucial', 'cruel', 'cruise', 'crumb', 'crush', 'crystal', 'cube',
  'cuckoo', 'cucumber', 'cuisine', 'culture', 'curb', 'curious', 'curl', 'current',
  'curtain', 'curve', 'cushion', 'custom', 'cycle', 'cypress', 'daily', 'damage',
  'damp', 'dance', 'danger', 'dare', 'dash', 'data', 'dawn', 'deal',
  'debate', 'debris', 'debt', 'decade', 'deck', 'declare', 'decor', 'decrease',
  'deep', 'defend', 'define', 'degree', 'delay', 'deliver', 'delta', 'demand',
  'denim', 'dense', 'dentist', 'depart', 'depth', 'derby', 'desert', 'design',
  'desk', 'detail', 'detect', 'device', 'devote', 'dial', 'diamond', 'diary',
  'diesel', 'diet', 'differ', 'digital', 'dignity', 'dilemma', 'dinner', 'dinosaur',
  'direct', 'dirt', 'disagree', 'discover', 'dish', 'dismiss', 'display', 'distance',
  'divert', 'divide', 'divorce', 'dizzy', 'doctor', 'document', 'dolphin', 'domain',
  'donate', 'donkey', 'donor', 'dose', 'double', 'dove', 'dozen', 'draft',
  'dragon', 'drama', 'drape', 'draw', 'dream', 'dress', 'drill', 'drink',
  'drive', 'drop', 'drum', 'duck', 'dumb', 'dune', 'during', 'dust',
  'duty', 'dwarf', 'dynamic', 'eager', 'eagle', 'early', 'earn', 'earth',
  'ease', 'echo', 'eclipse', 'ecology', 'economy', 'edge', 'edit', 'educate',
  'effort', 'eight', 'elbow', 'elder', 'electric', 'elegant', 'element', 'elephant',
  'elevate', 'elite', 'embark', 'embody', 'embrace', 'emerge', 'emotion', 'employ',
  'empower', 'empty', 'enable', 'enact', 'endless', 'endorse', 'enemy', 'energy',
  'enforce', 'engage', 'engine', 'enhance', 'enjoy', 'enlist', 'enough', 'enrich',
  'enroll', 'ensure', 'enter', 'entire', 'entry', 'envelope', 'episode', 'equal',
  'equip', 'erase', 'erode', 'error', 'erupt', 'escape', 'essay', 'essence',
  'estate', 'eternal', 'ethics', 'evening', 'event', 'every', 'evidence', 'evil',
  'evoke', 'evolve', 'exact', 'exam', 'example', 'excess', 'exchange', 'excite',
  'exclude', 'excuse', 'execute', 'exercise', 'exhaust', 'exhibit', 'exile', 'exist',
  'exotic', 'expand', 'expect', 'expire', 'explain', 'expose', 'express', 'extend',
  'extra', 'fabric', 'face', 'factor', 'fade', 'faint', 'fair', 'faith',
  'false', 'family', 'famous', 'fancy', 'fantasy', 'farm', 'fashion', 'fatal',
  'father', 'fatigue', 'fault', 'favor', 'feature', 'federal', 'feed', 'fellow',
  'female', 'fence', 'fern', 'festival', 'fetch', 'fever', 'fiber', 'fiction',
  'field', 'fifteen', 'fifty', 'fight', 'figure', 'filter', 'final', 'finger',
  'finish', 'fire', 'first', 'fiscal', 'fish', 'five', 'flag', 'flame',
  'flash', 'flavor', 'flee', 'flip', 'float', 'flock', 'floor', 'flow',
  'flower', 'fluid', 'foam', 'focus', 'fog', 'foil', 'fold', 'follow',
  'food', 'force', 'forest', 'forget', 'fork', 'forum', 'forward', 'fossil',
  'foster', 'found', 'fox', 'fragile', 'frame', 'free', 'freeze', 'frequent',
  'fresh', 'friend', 'fringe', 'frog', 'front', 'frown', 'frozen', 'fruit',
  'fuel', 'funny', 'furnace', 'fury', 'future', 'gadget', 'gain', 'galaxy',
  'gallery', 'game', 'garage', 'garden', 'garlic', 'garment', 'gasp', 'gate',
  'gather', 'gauge', 'gaze', 'gear', 'gem', 'gender', 'gene', 'general',
  'genius', 'gentle', 'genuine', 'gesture', 'ghost', 'giant', 'gift', 'giggle',
  'giraffe', 'girl', 'glad', 'glance', 'glare', 'glass', 'glide', 'glimpse',
  'globe', 'gloom', 'glory', 'glow', 'glue', 'goal', 'gold', 'goose',
  'gorilla', 'gospel', 'gossip', 'govern', 'gown', 'grab', 'grace', 'grain',
  'grant', 'grass', 'gravel', 'gravity', 'gray', 'great', 'green', 'grid',
  'grief', 'grill', 'grocery', 'group', 'grove', 'guard', 'guess', 'guide',
  'guilt', 'guitar', 'gulf', 'habit', 'hair', 'half', 'hammer', 'hamster',
  'happy', 'harbor', 'harsh', 'harvest', 'hawk', 'hazard', 'haze', 'health',
  'heart', 'heavy', 'hedge', 'height', 'hello', 'helmet', 'help', 'herb',
  'hidden', 'high', 'hill', 'hint', 'hip', 'hire', 'history', 'hobby',
  'hockey', 'hold', 'holiday', 'hollow', 'home', 'honey', 'hood', 'horn',
  'horror', 'horse', 'hospital', 'host', 'hotel', 'hour', 'house', 'hover',
  'hub', 'huge', 'human', 'humble', 'humor', 'hundred', 'hungry', 'hunt',
  'hurdle', 'hurry', 'husband', 'hybrid', 'ice', 'icon', 'idea', 'identify',
  'idle', 'ignore', 'image', 'impact', 'impose', 'improve', 'impulse', 'inch',
  'include', 'income', 'increase', 'index', 'indicate', 'indoor', 'industry', 'infant',
  'inflict', 'inform', 'inhale', 'inherit', 'initial', 'inject', 'injury', 'inmate',
  'inner', 'innocent', 'input', 'inquiry', 'insane', 'insect', 'inside', 'inspire',
  'install', 'intact', 'intense', 'invest', 'invite', 'involve', 'iron', 'island',
  'isolate', 'issue', 'ivory', 'jacket', 'jaguar', 'jazz', 'jealous', 'jeans',
  'jelly', 'jewel', 'join', 'joke', 'journey', 'judge', 'juice', 'jump',
  'jungle', 'junior', 'junk', 'kangaroo', 'keen', 'kernel', 'ketchup', 'kick',
  'kidney', 'kind', 'kingdom', 'kiss', 'kitchen', 'kite', 'kitten', 'kiwi',
  'knee', 'knife', 'knock', 'label', 'labor', 'ladder', 'lady', 'lake',
  'lamp', 'language', 'laptop', 'large', 'later', 'latin', 'laugh', 'laundry',
  'lava', 'lawn', 'lawsuit', 'layer', 'lazy', 'leader', 'leaf', 'learn',
  'leave', 'lecture', 'legal', 'legend', 'leisure', 'lemon', 'lend', 'length',
  'lens', 'leopard', 'lesson', 'letter', 'level', 'liar', 'liberty', 'library',
  'license', 'life', 'light', 'limb', 'limit', 'link', 'lion', 'liquid',
  'little', 'live', 'lizard', 'load', 'lobster', 'local', 'lock', 'logic',
  'lonely', 'loop', 'lottery', 'loud', 'lounge', 'love', 'loyal', 'lucky',
  'luggage', 'lumber', 'lunar', 'lunch', 'luxury', 'lyrics', 'machine', 'magic',
  'magnet', 'maid', 'major', 'mammal', 'manage', 'mandate', 'mango', 'mansion',
  'manual', 'maple', 'marble', 'march', 'margin', 'marine', 'market', 'marriage',
  'mask', 'master', 'match', 'material', 'matrix', 'matter', 'maximum', 'maze',
  'meadow', 'measure', 'meat', 'mechanic', 'medal', 'media', 'melody', 'melt',
  'member', 'memory', 'mention', 'menu', 'mercy', 'merge', 'merit', 'mesh',
  'message', 'metal', 'method', 'middle', 'midnight', 'milk', 'million', 'mimic',
  'mind', 'minimum', 'minor', 'minute', 'miracle', 'mirror', 'misery', 'mistake',
  'mixture', 'mobile', 'model', 'modify', 'moment', 'monitor', 'monkey', 'monster',
  'month', 'moon', 'moral', 'morning', 'mosquito', 'mother', 'motor', 'mountain',
  'mouse', 'movie', 'muffin', 'mule', 'multiply', 'muscle', 'museum', 'mushroom',
  'music', 'mutual', 'myself', 'mystery', 'myth', 'naive', 'napkin', 'narrow',
  'nasty', 'nation', 'nature', 'neck', 'negative', 'neglect', 'neither', 'nephew',
  'nerve', 'nest', 'network', 'neutral', 'never', 'news', 'nice', 'night',
  'noble', 'noise', 'nominee', 'noodle', 'normal', 'north', 'nose', 'notable',
] as const
